version: '3.3'

services:

  testy_db_server:
    container_name: testy_db_server
    image: mysql:latest
    restart: unless-stopped
    networks:
      - testy_net
    ports:
      - "3999:3306"
    environment:
      - MYSQL_DATABASE=testy_dev
      - MYSQL_USER=testy
      - MYSQL_PASSWORD=testy
      - MYSQL_ROOT_PASSWORD=toor 
      
  testy_db_admin:
    container_name: testy_db_admin
    image: adminer
    restart: always
    links:
      - "testy_db_server:testy_db_server"
    depends_on:
      - "testy_db_server"
    networks:
      - testy_net
    ports:
      - "1999:8080"

  testy_app:
    container_name: testy_app
    image: yilmazchef/testy:latest
    restart: always
    links:
    - "testy_db_server:testy_db_server"
    depends_on:
      - "testy_db_server"
    networks:
      - testy_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://testy_db_server:3306/testy_dev?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
    ports:
      - "9999:8080"

networks:
  testy_net:

