version: "3.9"
services:

  app:
    build: .
    ports:
      - "8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - devnet
    volumes:
      - devvol:/var/lib/testy

  db:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testydb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devnet
    volumes:
      - dbvol:/var/lib/postgresql/data

  dba:
    image: adminer:latest
    restart: always
    ports:
      - "8080"
    networks:
      - devnet

networks:
  pronet:
  devnet:


volumes:
  dbvol: {}
  devvol: {}
