version: '3.3'

services:

  testy_db_server:
    container_name: testy_db_server
    image: mysql:latest
    restart: unless-stopped
    networks:
      - check_net
    ports:
      - "3888:3306"
    environment:
      - MYSQL_DATABASE=testy_dev
      - MYSQL_USER=testy
      - MYSQL_PASSWORD=testy
      - MYSQL_ROOT_PASSWORD=toor 
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  testy_db_admin:
    container_name: testy_db_admin
    image: adminer
    restart: always
    links:
      - "testy_db_server:testy_db_server"
    depends_on:
      testy_db_server:
        condition: service_healthy
    networks:
      - check_net
    ports:
      - 1888:8080

  testy_app:
    container_name: testy_app
    image: yilmazchef/testy:latest
    restart: always
    links:
    - "testy_db_server:testy_db_server"
    depends_on:
      testy_db_server:
        condition: service_healthy
    networks:
      - check_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://testy_db_server:3306/testy_dev?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
    ports:
      - "8888:8080"

networks:
  check_net:
    attachable: true

