server:
  port: ${PORT:8888}
  # port: ${PORT:8443}
  # ssl:
  #   key-store: classpath:testy.p12
  #   key-store-password: P@ssw0rd
  #   keyStoreType: PKCS12

logging.level:
  org.atmosphere: warn

spring.mustache.check-template-location: false
vaadin.whitelisted-packages: com/vaadin,org/vaadin,it/vkod
vaadin.pnpm.enable: false

spring:
  profiles:
    active: "production"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_PASSWORD:chefsandbox@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:1q2w3e4rP@ssw0rd}
    properties:
      mail:
        smtp.auth: true
        smtp.starttls.enable: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/testy_dev?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:testy}
    password: ${SPRING_DATASOURCE_PASSWORD:testy}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
      roles: ${SPRING_SECURITY_ROLES}

  application:
    name: testy-pwa
  sql:
    init:
      mode: always

logging:
  level:
    org.zalando.logbook: TRACE




