server:
  port: ${PORT:8080}

logging.level:
  org.atmosphere: warn

spring.mustache.check-template-location: false
vaadin.whitelisted-packages: com/vaadin,org/vaadin,it/vkod
vaadin.pnpm.enable: false

spring:
  profiles:
    active: "production"
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        search:
          backend:
            directory:
              type: local-heap
  data:
    jpa:
      repositories:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp.auth: true
        starttls.enable: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/testydb?createDatabaseIfNotExist=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
      roles: ${SPRING_SECURITY_ROLES}

  application:
    name: testy-pwa
  sql:
    init:
      mode: always

logging:
  level:
    org.zalando.logbook: TRACE




